// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: post/rpc_get_posts_listing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPostsListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PerPage       string                 `protobuf:"bytes,1,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Offset        string                 `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsListingRequest) Reset() {
	*x = GetPostsListingRequest{}
	mi := &file_post_rpc_get_posts_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsListingRequest) ProtoMessage() {}

func (x *GetPostsListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_rpc_get_posts_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsListingRequest.ProtoReflect.Descriptor instead.
func (*GetPostsListingRequest) Descriptor() ([]byte, []int) {
	return file_post_rpc_get_posts_listing_proto_rawDescGZIP(), []int{0}
}

func (x *GetPostsListingRequest) GetPerPage() string {
	if x != nil {
		return x.PerPage
	}
	return ""
}

func (x *GetPostsListingRequest) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

type GetPostsListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          []*Post                `protobuf:"bytes,1,rep,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsListingResponse) Reset() {
	*x = GetPostsListingResponse{}
	mi := &file_post_rpc_get_posts_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsListingResponse) ProtoMessage() {}

func (x *GetPostsListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_rpc_get_posts_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsListingResponse.ProtoReflect.Descriptor instead.
func (*GetPostsListingResponse) Descriptor() ([]byte, []int) {
	return file_post_rpc_get_posts_listing_proto_rawDescGZIP(), []int{1}
}

func (x *GetPostsListingResponse) GetPost() []*Post {
	if x != nil {
		return x.Post
	}
	return nil
}

var File_post_rpc_get_posts_listing_proto protoreflect.FileDescriptor

const file_post_rpc_get_posts_listing_proto_rawDesc = "" +
	"\n" +
	" post/rpc_get_posts_listing.proto\x12\x02pb\x1a\x0fpost/post.proto\"K\n" +
	"\x16GetPostsListingRequest\x12\x19\n" +
	"\bper_page\x18\x01 \x01(\tR\aperPage\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\tR\x06offset\"7\n" +
	"\x17GetPostsListingResponse\x12\x1c\n" +
	"\x04post\x18\x01 \x03(\v2\b.pb.PostR\x04postB%Z#github.com/paweldyl/blog-backend/pbb\x06proto3"

var (
	file_post_rpc_get_posts_listing_proto_rawDescOnce sync.Once
	file_post_rpc_get_posts_listing_proto_rawDescData []byte
)

func file_post_rpc_get_posts_listing_proto_rawDescGZIP() []byte {
	file_post_rpc_get_posts_listing_proto_rawDescOnce.Do(func() {
		file_post_rpc_get_posts_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_rpc_get_posts_listing_proto_rawDesc), len(file_post_rpc_get_posts_listing_proto_rawDesc)))
	})
	return file_post_rpc_get_posts_listing_proto_rawDescData
}

var file_post_rpc_get_posts_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_post_rpc_get_posts_listing_proto_goTypes = []any{
	(*GetPostsListingRequest)(nil),  // 0: pb.GetPostsListingRequest
	(*GetPostsListingResponse)(nil), // 1: pb.GetPostsListingResponse
	(*Post)(nil),                    // 2: pb.Post
}
var file_post_rpc_get_posts_listing_proto_depIdxs = []int32{
	2, // 0: pb.GetPostsListingResponse.post:type_name -> pb.Post
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_post_rpc_get_posts_listing_proto_init() }
func file_post_rpc_get_posts_listing_proto_init() {
	if File_post_rpc_get_posts_listing_proto != nil {
		return
	}
	file_post_post_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_rpc_get_posts_listing_proto_rawDesc), len(file_post_rpc_get_posts_listing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_post_rpc_get_posts_listing_proto_goTypes,
		DependencyIndexes: file_post_rpc_get_posts_listing_proto_depIdxs,
		MessageInfos:      file_post_rpc_get_posts_listing_proto_msgTypes,
	}.Build()
	File_post_rpc_get_posts_listing_proto = out.File
	file_post_rpc_get_posts_listing_proto_goTypes = nil
	file_post_rpc_get_posts_listing_proto_depIdxs = nil
}
