// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: post/rpc_update_post.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *string                `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`
	ShortDesc     *string                `protobuf:"bytes,2,opt,name=short_desc,json=shortDesc,proto3,oneof" json:"short_desc,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_post_rpc_update_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_rpc_update_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_post_rpc_update_post_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatePostRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdatePostRequest) GetShortDesc() string {
	if x != nil && x.ShortDesc != nil {
		return *x.ShortDesc
	}
	return ""
}

func (x *UpdatePostRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type UpdatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResponse) Reset() {
	*x = UpdatePostResponse{}
	mi := &file_post_rpc_update_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResponse) ProtoMessage() {}

func (x *UpdatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_rpc_update_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResponse.ProtoReflect.Descriptor instead.
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return file_post_rpc_update_post_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

var File_post_rpc_update_post_proto protoreflect.FileDescriptor

const file_post_rpc_update_post_proto_rawDesc = "" +
	"\n" +
	"\x1apost/rpc_update_post.proto\x12\x02pb\x1a\x0fpost/post.proto\"\xa2\x01\n" +
	"\x11UpdatePostRequest\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x88\x01\x01\x12\"\n" +
	"\n" +
	"short_desc\x18\x02 \x01(\tH\x01R\tshortDesc\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x02R\vdescription\x88\x01\x01B\b\n" +
	"\x06_titleB\r\n" +
	"\v_short_descB\x0e\n" +
	"\f_description\"2\n" +
	"\x12UpdatePostResponse\x12\x1c\n" +
	"\x04post\x18\x01 \x01(\v2\b.pb.PostR\x04postB%Z#github.com/paweldyl/blog-backend/pbb\x06proto3"

var (
	file_post_rpc_update_post_proto_rawDescOnce sync.Once
	file_post_rpc_update_post_proto_rawDescData []byte
)

func file_post_rpc_update_post_proto_rawDescGZIP() []byte {
	file_post_rpc_update_post_proto_rawDescOnce.Do(func() {
		file_post_rpc_update_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_rpc_update_post_proto_rawDesc), len(file_post_rpc_update_post_proto_rawDesc)))
	})
	return file_post_rpc_update_post_proto_rawDescData
}

var file_post_rpc_update_post_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_post_rpc_update_post_proto_goTypes = []any{
	(*UpdatePostRequest)(nil),  // 0: pb.UpdatePostRequest
	(*UpdatePostResponse)(nil), // 1: pb.UpdatePostResponse
	(*Post)(nil),               // 2: pb.Post
}
var file_post_rpc_update_post_proto_depIdxs = []int32{
	2, // 0: pb.UpdatePostResponse.post:type_name -> pb.Post
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_post_rpc_update_post_proto_init() }
func file_post_rpc_update_post_proto_init() {
	if File_post_rpc_update_post_proto != nil {
		return
	}
	file_post_post_proto_init()
	file_post_rpc_update_post_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_rpc_update_post_proto_rawDesc), len(file_post_rpc_update_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_post_rpc_update_post_proto_goTypes,
		DependencyIndexes: file_post_rpc_update_post_proto_depIdxs,
		MessageInfos:      file_post_rpc_update_post_proto_msgTypes,
	}.Build()
	File_post_rpc_update_post_proto = out.File
	file_post_rpc_update_post_proto_goTypes = nil
	file_post_rpc_update_post_proto_depIdxs = nil
}
