// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: post/service_post.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_post_service_post_proto protoreflect.FileDescriptor

const file_post_service_post_proto_rawDesc = "" +
	"\n" +
	"\x17post/service_post.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1apost/rpc_create_post.proto\x1a\x17post/rpc_get_post.proto\x1a post/rpc_get_posts_listing.proto\x1a\x1apost/rpc_update_post.proto\x1a\x1apost/rpc_delete_post.proto2\xce\x02\n" +
	"\vPostService\x12=\n" +
	"\n" +
	"CreatePost\x12\x15.pb.CreatePostRequest\x1a\x16.pb.CreatePostResponse\"\x00\x124\n" +
	"\aGetPost\x12\x12.pb.GetPostRequest\x1a\x13.pb.GetPostResponse\"\x00\x12L\n" +
	"\x0fGetPostsListing\x12\x1a.pb.GetPostsListingRequest\x1a\x1b.pb.GetPostsListingResponse\"\x00\x12=\n" +
	"\n" +
	"UpdatePost\x12\x15.pb.UpdatePostRequest\x1a\x16.pb.UpdatePostResponse\"\x00\x12=\n" +
	"\n" +
	"DeletePost\x12\x15.pb.DeletePostRequest\x1a\x16.google.protobuf.Empty\"\x00B%Z#github.com/paweldyl/blog-backend/pbb\x06proto3"

var file_post_service_post_proto_goTypes = []any{
	(*CreatePostRequest)(nil),       // 0: pb.CreatePostRequest
	(*GetPostRequest)(nil),          // 1: pb.GetPostRequest
	(*GetPostsListingRequest)(nil),  // 2: pb.GetPostsListingRequest
	(*UpdatePostRequest)(nil),       // 3: pb.UpdatePostRequest
	(*DeletePostRequest)(nil),       // 4: pb.DeletePostRequest
	(*CreatePostResponse)(nil),      // 5: pb.CreatePostResponse
	(*GetPostResponse)(nil),         // 6: pb.GetPostResponse
	(*GetPostsListingResponse)(nil), // 7: pb.GetPostsListingResponse
	(*UpdatePostResponse)(nil),      // 8: pb.UpdatePostResponse
	(*emptypb.Empty)(nil),           // 9: google.protobuf.Empty
}
var file_post_service_post_proto_depIdxs = []int32{
	0, // 0: pb.PostService.CreatePost:input_type -> pb.CreatePostRequest
	1, // 1: pb.PostService.GetPost:input_type -> pb.GetPostRequest
	2, // 2: pb.PostService.GetPostsListing:input_type -> pb.GetPostsListingRequest
	3, // 3: pb.PostService.UpdatePost:input_type -> pb.UpdatePostRequest
	4, // 4: pb.PostService.DeletePost:input_type -> pb.DeletePostRequest
	5, // 5: pb.PostService.CreatePost:output_type -> pb.CreatePostResponse
	6, // 6: pb.PostService.GetPost:output_type -> pb.GetPostResponse
	7, // 7: pb.PostService.GetPostsListing:output_type -> pb.GetPostsListingResponse
	8, // 8: pb.PostService.UpdatePost:output_type -> pb.UpdatePostResponse
	9, // 9: pb.PostService.DeletePost:output_type -> google.protobuf.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_post_service_post_proto_init() }
func file_post_service_post_proto_init() {
	if File_post_service_post_proto != nil {
		return
	}
	file_post_rpc_create_post_proto_init()
	file_post_rpc_get_post_proto_init()
	file_post_rpc_get_posts_listing_proto_init()
	file_post_rpc_update_post_proto_init()
	file_post_rpc_delete_post_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_service_post_proto_rawDesc), len(file_post_service_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_service_post_proto_goTypes,
		DependencyIndexes: file_post_service_post_proto_depIdxs,
	}.Build()
	File_post_service_post_proto = out.File
	file_post_service_post_proto_goTypes = nil
	file_post_service_post_proto_depIdxs = nil
}
