// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: comment.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getCommentForUpdate = `-- name: GetCommentForUpdate :one
SELECT id, text, author_login, post_id FROM comments
WHERE id = $1 LIMIT 1 FOR NO KEY UPDATE
`

func (q *Queries) GetCommentForUpdate(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getCommentForUpdate, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.AuthorLogin,
		&i.PostID,
	)
	return i, err
}
