// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: post_likes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getPostLikeForUpdate = `-- name: GetPostLikeForUpdate :one
SELECT user_id, post_id, value, updated_at, created_at FROM posts_likes
WHERE user_id=$1 AND post_id=$2 LIMIT 1 FOR NO KEY UPDATE
`

type GetPostLikeForUpdateParams struct {
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

func (q *Queries) GetPostLikeForUpdate(ctx context.Context, arg GetPostLikeForUpdateParams) (PostsLike, error) {
	row := q.db.QueryRowContext(ctx, getPostLikeForUpdate, arg.UserID, arg.PostID)
	var i PostsLike
	err := row.Scan(
		&i.UserID,
		&i.PostID,
		&i.Value,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
