// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: post.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getPostForUpdate = `-- name: GetPostForUpdate :one
SELECT id, title, short_desc, description, author_login, likes_amount, dislikes_amount, edited_at, created_at FROM posts
WHERE id = $1 LIMIT 1 FOR NO KEY UPDATE
`

func (q *Queries) GetPostForUpdate(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostForUpdate, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ShortDesc,
		&i.Description,
		&i.AuthorLogin,
		&i.LikesAmount,
		&i.DislikesAmount,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}
