// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: post_likes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getPostLikeForUpdate = `-- name: GetPostLikeForUpdate :one
SELECT user_login, post_id, value FROM posts_likes
WHERE user_login=$1 AND post_id=$2 LIMIT 1 FOR NO KEY UPDATE
`

type GetPostLikeForUpdateParams struct {
	UserLogin string    `json:"user_login"`
	PostID    uuid.UUID `json:"post_id"`
}

func (q *Queries) GetPostLikeForUpdate(ctx context.Context, arg GetPostLikeForUpdateParams) (PostsLike, error) {
	row := q.db.QueryRowContext(ctx, getPostLikeForUpdate, arg.UserLogin, arg.PostID)
	var i PostsLike
	err := row.Scan(&i.UserLogin, &i.PostID, &i.Value)
	return i, err
}
