// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreatePostLike(ctx context.Context, arg CreatePostLikeParams) (PostsLike, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteComment(ctx context.Context, id uuid.UUID) error
	DeletePost(ctx context.Context, id uuid.UUID) error
	DeletePostLike(ctx context.Context, arg DeletePostLikeParams) error
	GetComment(ctx context.Context, id uuid.UUID) (Comment, error)
	GetCommentForUpdate(ctx context.Context, id uuid.UUID) (Comment, error)
	GetPost(ctx context.Context, id uuid.UUID) (Post, error)
	GetPostCommentsWithUsers(ctx context.Context, arg GetPostCommentsWithUsersParams) ([]GetPostCommentsWithUsersRow, error)
	GetPostForUpdate(ctx context.Context, id uuid.UUID) (Post, error)
	GetPostLike(ctx context.Context, arg GetPostLikeParams) (PostsLike, error)
	GetPostLikeForUpdate(ctx context.Context, arg GetPostLikeForUpdateParams) (PostsLike, error)
	GetPostsListing(ctx context.Context, arg GetPostsListingParams) ([]Post, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByLogin(ctx context.Context, login string) (User, error)
	GetUserForUpdate(ctx context.Context, id uuid.UUID) (User, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdatePostLike(ctx context.Context, arg UpdatePostLikeParams) (PostsLike, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
