// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: post_like/post_like.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeValue int32

const (
	LikeValue_LIKE_VALUE_UNSPECIFIED LikeValue = 0
	LikeValue_LIKE                   LikeValue = 1
	LikeValue_DISLIKE                LikeValue = 2
)

// Enum value maps for LikeValue.
var (
	LikeValue_name = map[int32]string{
		0: "LIKE_VALUE_UNSPECIFIED",
		1: "LIKE",
		2: "DISLIKE",
	}
	LikeValue_value = map[string]int32{
		"LIKE_VALUE_UNSPECIFIED": 0,
		"LIKE":                   1,
		"DISLIKE":                2,
	}
)

func (x LikeValue) Enum() *LikeValue {
	p := new(LikeValue)
	*p = x
	return p
}

func (x LikeValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LikeValue) Descriptor() protoreflect.EnumDescriptor {
	return file_post_like_post_like_proto_enumTypes[0].Descriptor()
}

func (LikeValue) Type() protoreflect.EnumType {
	return &file_post_like_post_like_proto_enumTypes[0]
}

func (x LikeValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LikeValue.Descriptor instead.
func (LikeValue) EnumDescriptor() ([]byte, []int) {
	return file_post_like_post_like_proto_rawDescGZIP(), []int{0}
}

type PostLike struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Value         LikeValue              `protobuf:"varint,3,opt,name=value,proto3,enum=pb.LikeValue" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostLike) Reset() {
	*x = PostLike{}
	mi := &file_post_like_post_like_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostLike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostLike) ProtoMessage() {}

func (x *PostLike) ProtoReflect() protoreflect.Message {
	mi := &file_post_like_post_like_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostLike.ProtoReflect.Descriptor instead.
func (*PostLike) Descriptor() ([]byte, []int) {
	return file_post_like_post_like_proto_rawDescGZIP(), []int{0}
}

func (x *PostLike) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostLike) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostLike) GetValue() LikeValue {
	if x != nil {
		return x.Value
	}
	return LikeValue_LIKE_VALUE_UNSPECIFIED
}

var File_post_like_post_like_proto protoreflect.FileDescriptor

const file_post_like_post_like_proto_rawDesc = "" +
	"\n" +
	"\x19post_like/post_like.proto\x12\x02pb\"a\n" +
	"\bPostLike\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\x12#\n" +
	"\x05value\x18\x03 \x01(\x0e2\r.pb.LikeValueR\x05value*>\n" +
	"\tLikeValue\x12\x1a\n" +
	"\x16LIKE_VALUE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04LIKE\x10\x01\x12\v\n" +
	"\aDISLIKE\x10\x02B%Z#github.com/paweldyl/blog-backend/pbb\x06proto3"

var (
	file_post_like_post_like_proto_rawDescOnce sync.Once
	file_post_like_post_like_proto_rawDescData []byte
)

func file_post_like_post_like_proto_rawDescGZIP() []byte {
	file_post_like_post_like_proto_rawDescOnce.Do(func() {
		file_post_like_post_like_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_like_post_like_proto_rawDesc), len(file_post_like_post_like_proto_rawDesc)))
	})
	return file_post_like_post_like_proto_rawDescData
}

var file_post_like_post_like_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_post_like_post_like_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_post_like_post_like_proto_goTypes = []any{
	(LikeValue)(0),   // 0: pb.LikeValue
	(*PostLike)(nil), // 1: pb.PostLike
}
var file_post_like_post_like_proto_depIdxs = []int32{
	0, // 0: pb.PostLike.value:type_name -> pb.LikeValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_post_like_post_like_proto_init() }
func file_post_like_post_like_proto_init() {
	if File_post_like_post_like_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_like_post_like_proto_rawDesc), len(file_post_like_post_like_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_post_like_post_like_proto_goTypes,
		DependencyIndexes: file_post_like_post_like_proto_depIdxs,
		EnumInfos:         file_post_like_post_like_proto_enumTypes,
		MessageInfos:      file_post_like_post_like_proto_msgTypes,
	}.Build()
	File_post_like_post_like_proto = out.File
	file_post_like_post_like_proto_goTypes = nil
	file_post_like_post_like_proto_depIdxs = nil
}
