// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: post_like/rpc_put_post_like.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutPostLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Value         LikeValue              `protobuf:"varint,2,opt,name=value,proto3,enum=pb.LikeValue" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPostLikeRequest) Reset() {
	*x = PutPostLikeRequest{}
	mi := &file_post_like_rpc_put_post_like_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPostLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPostLikeRequest) ProtoMessage() {}

func (x *PutPostLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_like_rpc_put_post_like_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPostLikeRequest.ProtoReflect.Descriptor instead.
func (*PutPostLikeRequest) Descriptor() ([]byte, []int) {
	return file_post_like_rpc_put_post_like_proto_rawDescGZIP(), []int{0}
}

func (x *PutPostLikeRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PutPostLikeRequest) GetValue() LikeValue {
	if x != nil {
		return x.Value
	}
	return LikeValue_LIKE_VALUE_UNSPECIFIED
}

type PutPostLikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostLike      *PostLike              `protobuf:"bytes,1,opt,name=post_like,json=postLike,proto3" json:"post_like,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPostLikeResponse) Reset() {
	*x = PutPostLikeResponse{}
	mi := &file_post_like_rpc_put_post_like_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPostLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPostLikeResponse) ProtoMessage() {}

func (x *PutPostLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_like_rpc_put_post_like_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPostLikeResponse.ProtoReflect.Descriptor instead.
func (*PutPostLikeResponse) Descriptor() ([]byte, []int) {
	return file_post_like_rpc_put_post_like_proto_rawDescGZIP(), []int{1}
}

func (x *PutPostLikeResponse) GetPostLike() *PostLike {
	if x != nil {
		return x.PostLike
	}
	return nil
}

var File_post_like_rpc_put_post_like_proto protoreflect.FileDescriptor

const file_post_like_rpc_put_post_like_proto_rawDesc = "" +
	"\n" +
	"!post_like/rpc_put_post_like.proto\x12\x02pb\x1a\x19post_like/post_like.proto\"R\n" +
	"\x12PutPostLikeRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12#\n" +
	"\x05value\x18\x02 \x01(\x0e2\r.pb.LikeValueR\x05value\"@\n" +
	"\x13PutPostLikeResponse\x12)\n" +
	"\tpost_like\x18\x01 \x01(\v2\f.pb.PostLikeR\bpostLikeB%Z#github.com/paweldyl/blog-backend/pbb\x06proto3"

var (
	file_post_like_rpc_put_post_like_proto_rawDescOnce sync.Once
	file_post_like_rpc_put_post_like_proto_rawDescData []byte
)

func file_post_like_rpc_put_post_like_proto_rawDescGZIP() []byte {
	file_post_like_rpc_put_post_like_proto_rawDescOnce.Do(func() {
		file_post_like_rpc_put_post_like_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_like_rpc_put_post_like_proto_rawDesc), len(file_post_like_rpc_put_post_like_proto_rawDesc)))
	})
	return file_post_like_rpc_put_post_like_proto_rawDescData
}

var file_post_like_rpc_put_post_like_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_post_like_rpc_put_post_like_proto_goTypes = []any{
	(*PutPostLikeRequest)(nil),  // 0: pb.PutPostLikeRequest
	(*PutPostLikeResponse)(nil), // 1: pb.PutPostLikeResponse
	(LikeValue)(0),              // 2: pb.LikeValue
	(*PostLike)(nil),            // 3: pb.PostLike
}
var file_post_like_rpc_put_post_like_proto_depIdxs = []int32{
	2, // 0: pb.PutPostLikeRequest.value:type_name -> pb.LikeValue
	3, // 1: pb.PutPostLikeResponse.post_like:type_name -> pb.PostLike
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_post_like_rpc_put_post_like_proto_init() }
func file_post_like_rpc_put_post_like_proto_init() {
	if File_post_like_rpc_put_post_like_proto != nil {
		return
	}
	file_post_like_post_like_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_like_rpc_put_post_like_proto_rawDesc), len(file_post_like_rpc_put_post_like_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_post_like_rpc_put_post_like_proto_goTypes,
		DependencyIndexes: file_post_like_rpc_put_post_like_proto_depIdxs,
		MessageInfos:      file_post_like_rpc_put_post_like_proto_msgTypes,
	}.Build()
	File_post_like_rpc_put_post_like_proto = out.File
	file_post_like_rpc_put_post_like_proto_goTypes = nil
	file_post_like_rpc_put_post_like_proto_depIdxs = nil
}
