// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: post_like/service_post_like.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PostLikeService_PutPostLike_FullMethodName    = "/pb.PostLikeService/PutPostLike"
	PostLikeService_GetPostLike_FullMethodName    = "/pb.PostLikeService/GetPostLike"
	PostLikeService_DeletePostLike_FullMethodName = "/pb.PostLikeService/DeletePostLike"
)

// PostLikeServiceClient is the client API for PostLikeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostLikeServiceClient interface {
	PutPostLike(ctx context.Context, in *PutPostLikeRequest, opts ...grpc.CallOption) (*PutPostLikeResponse, error)
	GetPostLike(ctx context.Context, in *GetPostLikeRequest, opts ...grpc.CallOption) (*GetPostLikeResponse, error)
	DeletePostLike(ctx context.Context, in *DeletePostLikeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type postLikeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostLikeServiceClient(cc grpc.ClientConnInterface) PostLikeServiceClient {
	return &postLikeServiceClient{cc}
}

func (c *postLikeServiceClient) PutPostLike(ctx context.Context, in *PutPostLikeRequest, opts ...grpc.CallOption) (*PutPostLikeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutPostLikeResponse)
	err := c.cc.Invoke(ctx, PostLikeService_PutPostLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postLikeServiceClient) GetPostLike(ctx context.Context, in *GetPostLikeRequest, opts ...grpc.CallOption) (*GetPostLikeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostLikeResponse)
	err := c.cc.Invoke(ctx, PostLikeService_GetPostLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postLikeServiceClient) DeletePostLike(ctx context.Context, in *DeletePostLikeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PostLikeService_DeletePostLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostLikeServiceServer is the server API for PostLikeService service.
// All implementations must embed UnimplementedPostLikeServiceServer
// for forward compatibility.
type PostLikeServiceServer interface {
	PutPostLike(context.Context, *PutPostLikeRequest) (*PutPostLikeResponse, error)
	GetPostLike(context.Context, *GetPostLikeRequest) (*GetPostLikeResponse, error)
	DeletePostLike(context.Context, *DeletePostLikeRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPostLikeServiceServer()
}

// UnimplementedPostLikeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostLikeServiceServer struct{}

func (UnimplementedPostLikeServiceServer) PutPostLike(context.Context, *PutPostLikeRequest) (*PutPostLikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutPostLike not implemented")
}
func (UnimplementedPostLikeServiceServer) GetPostLike(context.Context, *GetPostLikeRequest) (*GetPostLikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostLike not implemented")
}
func (UnimplementedPostLikeServiceServer) DeletePostLike(context.Context, *DeletePostLikeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePostLike not implemented")
}
func (UnimplementedPostLikeServiceServer) mustEmbedUnimplementedPostLikeServiceServer() {}
func (UnimplementedPostLikeServiceServer) testEmbeddedByValue()                         {}

// UnsafePostLikeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostLikeServiceServer will
// result in compilation errors.
type UnsafePostLikeServiceServer interface {
	mustEmbedUnimplementedPostLikeServiceServer()
}

func RegisterPostLikeServiceServer(s grpc.ServiceRegistrar, srv PostLikeServiceServer) {
	// If the following call pancis, it indicates UnimplementedPostLikeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostLikeService_ServiceDesc, srv)
}

func _PostLikeService_PutPostLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutPostLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostLikeServiceServer).PutPostLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostLikeService_PutPostLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostLikeServiceServer).PutPostLike(ctx, req.(*PutPostLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostLikeService_GetPostLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostLikeServiceServer).GetPostLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostLikeService_GetPostLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostLikeServiceServer).GetPostLike(ctx, req.(*GetPostLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostLikeService_DeletePostLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostLikeServiceServer).DeletePostLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostLikeService_DeletePostLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostLikeServiceServer).DeletePostLike(ctx, req.(*DeletePostLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostLikeService_ServiceDesc is the grpc.ServiceDesc for PostLikeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostLikeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PostLikeService",
	HandlerType: (*PostLikeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutPostLike",
			Handler:    _PostLikeService_PutPostLike_Handler,
		},
		{
			MethodName: "GetPostLike",
			Handler:    _PostLikeService_GetPostLike_Handler,
		},
		{
			MethodName: "DeletePostLike",
			Handler:    _PostLikeService_DeletePostLike_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post_like/service_post_like.proto",
}
