// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: post_like/service_post_like.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_post_like_service_post_like_proto protoreflect.FileDescriptor

const file_post_like_service_post_like_proto_rawDesc = "" +
	"\n" +
	"!post_like/service_post_like.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a!post_like/rpc_put_post_like.proto\x1a!post_like/rpc_get_post_like.proto\x1a$post_like/rpc_delete_post_like.proto2\xdc\x01\n" +
	"\x0fPostLikeService\x12@\n" +
	"\vPutPostLike\x12\x16.pb.PutPostLikeRequest\x1a\x17.pb.PutPostLikeResponse\"\x00\x12@\n" +
	"\vGetPostLike\x12\x16.pb.GetPostLikeRequest\x1a\x17.pb.GetPostLikeResponse\"\x00\x12E\n" +
	"\x0eDeletePostLike\x12\x19.pb.DeletePostLikeRequest\x1a\x16.google.protobuf.Empty\"\x00B%Z#github.com/paweldyl/blog-backend/pbb\x06proto3"

var file_post_like_service_post_like_proto_goTypes = []any{
	(*PutPostLikeRequest)(nil),    // 0: pb.PutPostLikeRequest
	(*GetPostLikeRequest)(nil),    // 1: pb.GetPostLikeRequest
	(*DeletePostLikeRequest)(nil), // 2: pb.DeletePostLikeRequest
	(*PutPostLikeResponse)(nil),   // 3: pb.PutPostLikeResponse
	(*GetPostLikeResponse)(nil),   // 4: pb.GetPostLikeResponse
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_post_like_service_post_like_proto_depIdxs = []int32{
	0, // 0: pb.PostLikeService.PutPostLike:input_type -> pb.PutPostLikeRequest
	1, // 1: pb.PostLikeService.GetPostLike:input_type -> pb.GetPostLikeRequest
	2, // 2: pb.PostLikeService.DeletePostLike:input_type -> pb.DeletePostLikeRequest
	3, // 3: pb.PostLikeService.PutPostLike:output_type -> pb.PutPostLikeResponse
	4, // 4: pb.PostLikeService.GetPostLike:output_type -> pb.GetPostLikeResponse
	5, // 5: pb.PostLikeService.DeletePostLike:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_post_like_service_post_like_proto_init() }
func file_post_like_service_post_like_proto_init() {
	if File_post_like_service_post_like_proto != nil {
		return
	}
	file_post_like_rpc_put_post_like_proto_init()
	file_post_like_rpc_get_post_like_proto_init()
	file_post_like_rpc_delete_post_like_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_like_service_post_like_proto_rawDesc), len(file_post_like_service_post_like_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_like_service_post_like_proto_goTypes,
		DependencyIndexes: file_post_like_service_post_like_proto_depIdxs,
	}.Build()
	File_post_like_service_post_like_proto = out.File
	file_post_like_service_post_like_proto_goTypes = nil
	file_post_like_service_post_like_proto_depIdxs = nil
}
