// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: user/service_user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_service_user_proto protoreflect.FileDescriptor

const file_user_service_user_proto_rawDesc = "" +
	"\n" +
	"\x17user/service_user.proto\x12\x02pb\x1a\x1auser/rpc_create_user.proto\x1a\x17user/rpc_get_user.proto\x1a\x1auser/rpc_update_user.proto\x1a\x19user/rpc_login_user.proto\x1a\x1cuser/rpc_refresh_token.proto2\xc2\x02\n" +
	"\vUserService\x12=\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"\x00\x124\n" +
	"\aGetUser\x12\x12.pb.GetUserRequest\x1a\x13.pb.GetUserResponse\"\x00\x12=\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"\x00\x12:\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"\x00\x12C\n" +
	"\fRefreshToken\x12\x17.pb.RefreshTokenRequest\x1a\x18.pb.RefreshTokenResponse\"\x00B%Z#github.com/paweldyl/blog-backend/pbb\x06proto3"

var file_user_service_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),    // 0: pb.CreateUserRequest
	(*GetUserRequest)(nil),       // 1: pb.GetUserRequest
	(*UpdateUserRequest)(nil),    // 2: pb.UpdateUserRequest
	(*LoginUserRequest)(nil),     // 3: pb.LoginUserRequest
	(*RefreshTokenRequest)(nil),  // 4: pb.RefreshTokenRequest
	(*CreateUserResponse)(nil),   // 5: pb.CreateUserResponse
	(*GetUserResponse)(nil),      // 6: pb.GetUserResponse
	(*UpdateUserResponse)(nil),   // 7: pb.UpdateUserResponse
	(*LoginUserResponse)(nil),    // 8: pb.LoginUserResponse
	(*RefreshTokenResponse)(nil), // 9: pb.RefreshTokenResponse
}
var file_user_service_user_proto_depIdxs = []int32{
	0, // 0: pb.UserService.CreateUser:input_type -> pb.CreateUserRequest
	1, // 1: pb.UserService.GetUser:input_type -> pb.GetUserRequest
	2, // 2: pb.UserService.UpdateUser:input_type -> pb.UpdateUserRequest
	3, // 3: pb.UserService.LoginUser:input_type -> pb.LoginUserRequest
	4, // 4: pb.UserService.RefreshToken:input_type -> pb.RefreshTokenRequest
	5, // 5: pb.UserService.CreateUser:output_type -> pb.CreateUserResponse
	6, // 6: pb.UserService.GetUser:output_type -> pb.GetUserResponse
	7, // 7: pb.UserService.UpdateUser:output_type -> pb.UpdateUserResponse
	8, // 8: pb.UserService.LoginUser:output_type -> pb.LoginUserResponse
	9, // 9: pb.UserService.RefreshToken:output_type -> pb.RefreshTokenResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_service_user_proto_init() }
func file_user_service_user_proto_init() {
	if File_user_service_user_proto != nil {
		return
	}
	file_user_rpc_create_user_proto_init()
	file_user_rpc_get_user_proto_init()
	file_user_rpc_update_user_proto_init()
	file_user_rpc_login_user_proto_init()
	file_user_rpc_refresh_token_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_user_proto_rawDesc), len(file_user_service_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_user_proto_goTypes,
		DependencyIndexes: file_user_service_user_proto_depIdxs,
	}.Build()
	File_user_service_user_proto = out.File
	file_user_service_user_proto_goTypes = nil
	file_user_service_user_proto_depIdxs = nil
}
