// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: comment/service_comment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_comment_service_comment_proto protoreflect.FileDescriptor

const file_comment_service_comment_proto_rawDesc = "" +
	"\n" +
	"\x1dcomment/service_comment.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a comment/rpc_create_comment.proto\x1a#comment/rpc_get_post_comments.proto\x1a comment/rpc_update_comment.proto\x1a comment/rpc_delete_comment.proto2\xb3\x02\n" +
	"\x0eCommentService\x12F\n" +
	"\rCreateComment\x12\x18.pb.CreateCommentRequest\x1a\x19.pb.CreateCommentResponse\"\x00\x12L\n" +
	"\x0fGetPostComments\x12\x1a.pb.GetPostCommentsRequest\x1a\x1b.pb.GetPostCommentsResponse\"\x00\x12F\n" +
	"\rUpdateComment\x12\x18.pb.UpdateCommentRequest\x1a\x19.pb.UpdateCommentResponse\"\x00\x12C\n" +
	"\rDeleteComment\x12\x18.pb.DeleteCommentRequest\x1a\x16.google.protobuf.Empty\"\x00B%Z#github.com/paweldyl/blog-backend/pbb\x06proto3"

var file_comment_service_comment_proto_goTypes = []any{
	(*CreateCommentRequest)(nil),    // 0: pb.CreateCommentRequest
	(*GetPostCommentsRequest)(nil),  // 1: pb.GetPostCommentsRequest
	(*UpdateCommentRequest)(nil),    // 2: pb.UpdateCommentRequest
	(*DeleteCommentRequest)(nil),    // 3: pb.DeleteCommentRequest
	(*CreateCommentResponse)(nil),   // 4: pb.CreateCommentResponse
	(*GetPostCommentsResponse)(nil), // 5: pb.GetPostCommentsResponse
	(*UpdateCommentResponse)(nil),   // 6: pb.UpdateCommentResponse
	(*emptypb.Empty)(nil),           // 7: google.protobuf.Empty
}
var file_comment_service_comment_proto_depIdxs = []int32{
	0, // 0: pb.CommentService.CreateComment:input_type -> pb.CreateCommentRequest
	1, // 1: pb.CommentService.GetPostComments:input_type -> pb.GetPostCommentsRequest
	2, // 2: pb.CommentService.UpdateComment:input_type -> pb.UpdateCommentRequest
	3, // 3: pb.CommentService.DeleteComment:input_type -> pb.DeleteCommentRequest
	4, // 4: pb.CommentService.CreateComment:output_type -> pb.CreateCommentResponse
	5, // 5: pb.CommentService.GetPostComments:output_type -> pb.GetPostCommentsResponse
	6, // 6: pb.CommentService.UpdateComment:output_type -> pb.UpdateCommentResponse
	7, // 7: pb.CommentService.DeleteComment:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_comment_service_comment_proto_init() }
func file_comment_service_comment_proto_init() {
	if File_comment_service_comment_proto != nil {
		return
	}
	file_comment_rpc_create_comment_proto_init()
	file_comment_rpc_get_post_comments_proto_init()
	file_comment_rpc_update_comment_proto_init()
	file_comment_rpc_delete_comment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_service_comment_proto_rawDesc), len(file_comment_service_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comment_service_comment_proto_goTypes,
		DependencyIndexes: file_comment_service_comment_proto_depIdxs,
	}.Build()
	File_comment_service_comment_proto = out.File
	file_comment_service_comment_proto_goTypes = nil
	file_comment_service_comment_proto_depIdxs = nil
}
